# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Override values for 5g-ran-sim helm chart
# 5g-ran-sim Helm Charts values - https://gerrit.opencord.org/sdcore-helm-charts/5g-ran-sim/values.yaml

5g-ran-sim:
  enable: ${ENABLE_RANSIM}
  resources:
    enabled: false
  images:
    repository: "registry.opennetworking.org/docker.io/"
    #tags:
    #  gnbsim: 5gc-gnbsim:0.0.1-dev-local5
  config:
    gnbsim:
      singleInterface: false #default multiInterface. Works well for AIAB
      execInParallel: false #run all profiles in parallel
      goProfile:
        enable: false #enable/disable golang profile in gnbsim
        port: 5000
      httpServer:
        enable: false #enable httpServer in gnbsim
        port: 6000
      yamlCfgFiles:
        gnb.conf:
          logger:
            logLevel: trace # trace, debug, info, warn, error, fatal, panic
          configuration:
             #gnbs: # pool of gNodeBs
             #  gnb1:
             #    n3IpAddr: "POD_IP" # set if singleInterface is true
              gnbs: # pool of gNodeBs
               gnb1:
                 defaultAmf:
                   hostName: amf # Host name of AMF
                   port: 38412 # AMF port

              # See https://github.com/omec-project/gnbsim for
              # Documentation on supported profiles and their parameters
              # Profile 2 (pdusessest) is typically enabled by default
              profiles:
              - profileType: register           # UE Registration
                profileName: profile1
                enable: false
                gnbName: gnb1
                execInParallel: false
                startImsi: 208930100007487
                ueCount: 5                
                defaultAs: "192.168.250.1"
                perUserTimeout: 100       
                plmnId:                   
                  mcc: 208                
                  mnc: 93                 
                opc: "981d464c7c52eb6e5036234984ad0bcf"
                key: "5122250214c33e723a5dd523fc145fc0"
                sequenceNumber: "16f3b3f70fc2"

              - profileType: pdusessest         # UE Initiated Session
                profileName: profile2
                enable: true
                gnbName: gnb1
                execInParallel: false
                startImsi: 208930100007487
                ueCount: 5
                defaultAs: "192.168.250.1"
                perUserTimeout: 100
                plmnId:
                  mcc: 208
                  mnc: 93
                dataPktCount: 5
                opc: "981d464c7c52eb6e5036234984ad0bcf"
                key: "5122250214c33e723a5dd523fc145fc0"
                sequenceNumber: "16f3b3f70fc2"

              - profileType: anrelease          # AN Release
                profileName: profile3
                enable: false
                execInParallel: false
                gnbName: gnb1
                startImsi: 208930100007497
                ueCount: 5
                defaultAs: "192.168.250.1"
                perUserTimeout: 100 
                plmnId:
                  mcc: 208
                  mnc: 93
                opc: "981d464c7c52eb6e5036234984ad0bcf"
                key: "5122250214c33e723a5dd523fc145fc0"
                sequenceNumber: "16f3b3f70fc2"

              - profileType: uetriggservicereq  # UE Initiated Service Request
                profileName: profile4
                enable: false
                gnbName: gnb1
                execInParallel: false
                startImsi: 208930100007497
                ueCount: 5
                plmnId:
                  mcc: 208
                  mnc: 93
                defaultAs: "192.168.250.1"
                perUserTimeout: 100
                opc: "981d464c7c52eb6e5036234984ad0bcf"
                key: "5122250214c33e723a5dd523fc145fc0"
                sequenceNumber: "16f3b3f70fc2"

              - profileType: deregister         # UE Initiated De-registration
                profileName: profile5
                enable: false
                gnbName: gnb1
                execInParallel: false
                startImsi: 208930100007497
                ueCount: 5
                defaultAs: "192.168.250.1"
                perUserTimeout: 100
                plmnId:
                  mcc: 208
                  mnc: 93
                opc: "981d464c7c52eb6e5036234984ad0bcf"
                key: "5122250214c33e723a5dd523fc145fc0"
                sequenceNumber: "16f3b3f70fc2"

              - profileType: nwtriggeruedereg   # N/W Initiated De-registration
                profileName: profile6
                enable: false
                gnbName: gnb1
                execInParallel: false
                startImsi: 208930100007497
                ueCount: 5 
                defaultAs: "192.168.250.1"
                perUserTimeout: 100 
                plmnId: 
                  mcc: 208 
                  mnc: 93 
                opc: "981d464c7c52eb6e5036234984ad0bcf"
                key: "5122250214c33e723a5dd523fc145fc0"
                sequenceNumber: "16f3b3f70fc2"

              - profileType: uereqpdusessrelease  # UE Initiated Session Release
                profileName: profile7 
                enable: false 
                gnbName: gnb1 
                execInParallel: false
                startImsi: 208930100007497
                ueCount: 5 
                plmnId:
                  mcc: 208 
                  mnc: 93
                defaultAs: "192.168.250.1"
                perUserTimeout: 100
                opc: "981d464c7c52eb6e5036234984ad0bcf"
                key: "5122250214c33e723a5dd523fc145fc0"
                sequenceNumber: "16f3b3f70fc2"

              # Custom Profiles that iterate through
              # combinations of the supported Profiles
              customProfiles:
                customProfiles1:
                  profileType: custom
                  profileName: custom1
                  enable: false
                  execInParallel: false
                  stepTrigger: false # wait for trigger to move to next step
                  gnbName: gnb1
                  startImsi: 208930100007487
                  ueCount: 30
                  defaultAs: "192.168.250.1"
                  opc: "981d464c7c52eb6e5036234984ad0bcf"
                  key: "5122250214c33e723a5dd523fc145fc0"
                  sequenceNumber: "16f3b3f70fc2"
                  plmnId:
                    mcc: 208
                    mnc: 93
                  # Starting iteration; step through until quit
                  startiteration: iteration1
                  iterations:
                    - "name": "iteration1"
                      "1": "REGISTRATION-PROCEDURE 5"
                      "2": "PDU-SESSION-ESTABLISHMENT-PROCEDURE 5"
                      "3": "USER-DATA-PACKET-GENERATION-PROCEDURE 10"
                      "next":  "iteration2"
                    - "name": "iteration2"
                      "1": "AN-RELEASE-PROCEDURE 10"
                      "2": "UE-TRIGGERED-SERVICE-REQUEST-PROCEDURE 5"
                      "repeat": 0   # default = 0 (execute once)
                      "next":  "iteration3"
                    - "name": "iteration3"
                      "1": "UE-INITIATED-DEREGISTRATION-PROCEDURE 10"
                      "repeat": 0     # default=0 (execute once)
                      "next":  "quit" # default=quit (no more iterations)

