# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# This is the network config for enb interface
network:
  ethernets:
    enb:
      dhcp4: false
      addresses: [192.168.251.3/24]
      routes:
        - to: 192.168.252.0/24
          via: 192.168.251.1
  version: 2
