# SPDX-FileCopyrightText: 2022-present Intel Corporation
# 
# SPDX-License-Identifier: Apache-2.0

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metricfunc
  namespace: omec
spec:
  endpoints:
    - path: /metrics
      port: prometheus-exporter
  namespaceSelector:
    matchNames:
      - omec
  selector:
    matchLabels:
      app: metricfunc
