# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

global:
  atomix:
    store:
      consensus:
        enabled: true
        name: ""

import:
  aether-roc-gui:
    v2-1:
      enabled: true
    v2-0: # This is the new v2, not the old one...
      enabled: false
  sdcore-adapter:
    v2-1:
      enabled: true
    v2-0: # This is the new v2, not the old one...
      enabled: false
  sdcore-test-dummy:
    enabled: false
  prometheus:
    acc:
      enabled: false
    amp:
      enabled: false
    ace:
      enabled: false
  demo-exporter:
    enabled: false
  prom-label-proxy:
    acc:
      enabled: false
    amp:
      enabled: false
  subscriber-proxy:
    enabled: false

aether-roc-gui-v2-1:
  ingress:
    enabled: false
  grafana:
    proxyEnabled: false
  prometheus:
    acc:
      proxyEnabled: false
    amp:
      proxyEnabled: false
    site: []
  service:
    type: NodePort

prometheus-amp:
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false
prometheus-acc:
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false
prometheus-ace:
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false

sdcore-adapter-v2-1:
  defaultTarget: aiab-enterprise

enterprises:
  - id: aiab-enterprise
    name: AiaB Enterprise
    lat: 52.5150
    long: 13.3885
  - id: defaultent
    name: Default Enterprise
